### ISSUE TITLE
Dynamic attributes

### ISSUE THREAD

**Issue by rotsee** [gagan-bansal/geojson2svg#11]
Thanks for a handy lib! It would be really nice id it was possible to assign attributes depending on some geojson data, either by mapping json attrubites to SVG attributes, or by passing the relevant json attribute to the callback function, so that something like the following was possible:

    {"type":"Feature","properties":{"ID":"foo"},"geometry":{"type":"MultiPolygon","coordinates":...

=>

    <path data-id="foo" d="...

**Comment by gagan-bansal** [comment]
Nice suggestion!
Right now it generates "id" as 
```javascript
var geojson2svg = require('geojson2svg');
var converter = geojson2svg(options);
var svgString = converter.convert(geojson,{
  attributes: {id: 'foo', class: 'bar'}  
});
```
or if feature itself has id, like 
```javascript 
var feature = {
  type: "Feature",
  id: "foo",
  geometry: {...},
  properties: {name : 'myname'}
}
```
and output would be 
```
<path id="foo" class="bar" d="....."  ></path>
```

Your suggestion is nice I'll add "id" fallback on the "id" in properties of feature.
Thanks

**Comment by rotsee** [comment]
Beautiful!

**Comment by gagan-bansal** [comment]
@rotsee Please let me know if any other improvement required.
