### ISSUE TITLE
No possibility to convert Point as circle

### ISSUE THREAD

**Issue by franto** [gagan-bansal/geojson2svg#15]
It seems there is bug and even pointAsCircle: true returns always path instead of circle. 

Problem is in instance.js in convertGeometry line 82 (return jsonToSvgElement(json,geom.type); doesnt call "opt" parameter, so in function jsonToSvgElement variable forcePath is always true.

Now converted result looks like:
`<path cx="M611.5267122181064" cy="562.2759809701495 m-5" r="5" />`

Expected result:
`<circle cx="611.5267122181064" cy="562.2759809701495" r="5" />`

**Comment by gagan-bansal** [comment]
Thanks @franto for pointing out this bug. I have fixed it and added test case also.
