### ISSUE TITLE
attributes again

### ISSUE THREAD

**Issue by allochi** [gagan-bansal/geojson2svg#17]
hi @gagan-bansal,

Thanks a lot for the merge. I have one question, currently you allow either `attributes` by `properties` or by passing a `json` object, which mean I can't use both (in my case I need both), could this behavior change to something like

```js
{
    "attributes": {
        static: {"class": "mapstyle"},
        dynamic: ["properties.foo", "properties.bar"]
    }
}
```

I'm sorry if I didn't mention this earlier, but the other branch used to read the property data and add its content as attributes, which allowed me to use both. I didn't read your source code yet, so I could be missing something.

Thanks!

**Comment by gagan-bansal** [comment]
I'll think how suitably it should be implemented. Your point is correct I'll implement in one or two days.

**Comment by gagan-bansal** [comment]
I have implemented like this:
* **attributes:**  Attributes which are required to attach as SVG attributes from features can be passed here as list of path in feature or json object for static attributes, like shown here

    **dynamic**  ``` {"attributes": ["properties.foo", "properties.bar"]}```

    output: ``` [<path foo="fooVal-1"  bar="barVal-1" d="M0,0 20,10 106,40"/>] ``` 

    or **static** ``` {"attributes": {"class": "mapstyle"}}```
    
    outut: ```'<path class="mapstyle" d="M0,0 20,10 106,40"/>'```

    or **dynamic** and **static** both
    
      {attributes: [
        {   
          property: 'properties.foo',
          type: 'dynamic',
          key: 'id'
        }, {
          property: 'properties.baz',
          type: 'dynamic'
        }, {
          property: 'bar',
          value: 'barStatic',
          type: 'static'
        }]
      })


    output: ``` [ '<path d="M128,128 128.00638801979818,127.99361198020182" id="fooVal-1" baz="bazVal-1" bar="barStatic"/>'] ```


    Note: If a feature does not have value at the mentioned path then the attribute key would not be attached to svg string and even error would not be thrown.

**Comment by allochi** [comment]
@gagan-bansal 

Thanks man, you are the best!

Now, I hate to spoil that for you, but I think that, there is one extra change needed, when `json` data is received from a server, there is no control over the property names, it's up to the provider, and same goes for the libraries, this is a mapping issue. 

I would like to suggest that you add a name for the dynamic property, for example to do something like this:

```js
{ attributes: [
    {
        property: 'properties.english_name', // the property name
        type: 'dynamic',
        name: 'title' // the attribute name
    }
] }
```

This way, when the API sends something like region names in multiple languages, we can map the desired property, e.g `english_name` to the needed attribute `title`.

for now, looping through the data to add the property `title` to the feature properties.

Seriously man, great job! and thanks a lot!

**Comment by gagan-bansal** [comment]
Welocme, that I have already added in my last commit. Just use `key`, like:
```
{ attributes: [
    {
        property: 'properties.english_name', // the property name
        type: 'dynamic',
        key: 'title' // the attribute name
    }
] }
```
