### ISSUE TITLE
Add attributes from Geojson to SVG

### ISSUE THREAD

**Issue by Mohsen62m** [gagan-bansal/geojson2svg#21]
Hello,

Can we add some attributes from Geojson to SVG, with providing which properties or geometries in Geojson we need to add in SVG, with "geojson2svg"?

**Comment by gagan-bansal** [comment]
Yes you can add, here is example:
```javascript
var geojson2svg = require('geojson2svg');    
var converter = geojson2svg({     
  attributes: ["properties.foo", "bar"]     
})    
var line = {     
  type: 'Feature',    
  geometry: {     
    type:'LineString',    
    coordinates:[[10,10],[15,20],[30,10]]     
  },    
  properties: {     
    foo: 'fooval'     
  },    
  "bar": "barval"     
}     
var svgStrings = converter.convert(line)    
    
console.log(converter.convert(line))    
// output     
// [ '<path d="M128.00006388019798,127.99993611980202 128.00009582029696,127.99987223960403 128.00019164059395,127.99993611980202" foo="fooval" bar="barval"/>' ]
```
You can read more about `attributes` in option's section of README.
Feel free to discuss any issue related to geojson2svg.

**Comment by gagan-bansal** [comment]
Let me check that.
Are you able to run above example?

**Comment by Mohsen62m** [comment]
I could not work on it. In the first time I will work on it.
Thank you for your attention.

**Comment by gagan-bansal** [comment]
Feel free to ask any doubt. Right now I am closing the issue.
