### ISSUE TITLE
"Check my blog maps-on-blackboard for more detailed examples." 404ing

### ISSUE THREAD

**Issue by matkoniecz** [gagan-bansal/geojson2svg#25]
http://maps-on-blackboard.com/tag/geojson2svg/ appears to be down

**Comment by gagan-bansal** [comment]
Yes I have to fix it. This is the source https://github.com/maps-on-blackboard
I was using a static site generator for creating this, there was some issue over there. I have to move the content to some other static site generator. 
As now you have reported, I should fix it, may be this week itself.

Thanks,
Gagan

**Comment by gagan-bansal** [comment]
Please check this now:
http://maps-on-blackboard.github.io/tag/geojson2svg/
I have removed the custom domain entry from github pages.

**Comment by matkoniecz** [comment]
http://maps-on-blackboard.github.io/tag/geojson2svg/ works, readme link is still 404ing

**Comment by gagan-bansal** [comment]
@matkoniecz thank you for informing, I'll correct it.

**Comment by gagan-bansal** [comment]
Replaced the custom domain link to maps-on-blackboard.github.io from every where.
Please check it now.

**Comment by gagan-bansal** [comment]
Corrected now. You had mentioned earlier also about README but I could not get that time. My mistake, I saw in my blog some hyperlinks were with maps-on-blackboard.com and corrected those. 

@matkoniecz Thank you very much for your time and support.

**Comment by matkoniecz** [comment]
Fixed!
